---
title: "dplyr Practice Questions"
output: html_notebook
---

```{r}

library(tidyverse)
library(dplyr)
library(stringr)
library(janitor)
library(here)

```



```{r}
salaries <- read_csv("data/salaries.csv")


```


```{r}
names(salaries)

```

Q1

```{r}

# Use select to see the beginning salary variable and the current salary variable.

salaries %>%
  select(beginning_salary, current_salary)

```


Q2

```{r}
# Use filter to see the employees aged over 50, who have a salary over £20,000

salaries %>%
  filter(age > 50) %>%
  filter(current_salary > 20000)
   


```

Q3

```{r}
# Use arrange to order by the data so that the highest salaries are first.

salaries %>%
  arrange(desc(current_salary)) %>%
  select(current_salary)
  


```

Q4

```{r}
# Use mutate to make a new variables beginning_salary_pence and current_salary_pence. These should have the corresponding salaries in pence instead of pounds.


salaries %>%
  mutate(beginning_salary_pence  = beginning_salary * 100,
         current_salary_pence = current_salary * 100)

```

Q5

```{r}
# Use summarise to find the maximum age and the minimum age.

salaries %>%
  summarise(max(age), min(age))

```

Q6

```{r}
# Find the minimum salary and the maximum salary

salaries %>%
  summarise(max(current_salary), min(current_salary))
  

```

Q7

```{r}
# Find all the employees aged under 30

salaries %>%
  group_by(age) %>%
  filter(age < 30)


```

Q8

```{r}
# Order the data in terms of increasing educational level where ties are broken using age.


salaries %>%
  arrange(educational_level, age) 
  

```

Q9

```{r}
#Drop all the non-numeric variables in the tibble

salaries %>%
  select_if(is.character)
  
```

Q10

```{r}
# Find all employees with either less than 2 years work experience or an education level below 12

salaries %>%
  filter(work_experience < 2 & educational_level < 12)


```

Q11

```{r}

# Transform the salary variables so they measure how many 1000s of pounds each salary is

salaries %>%
  mutate(current_salary/1000)

```

Q12

```{r}

#Find all the females employees with an employment category of ‘security officer’

salaries %>%
   filter(gender == 'female', 
          employment_category == 'security officer') %>%
          select(gender, employment_category)
   
  


```


Q13

```{r}

# Find the average salary across each employment category

salaries %>%
  group_by(employment_category) %>%
  summarise(avg_salary = mean(current_salary))


```

Q14

```{r}

# What is the average salary across each employment category for just the males?

salaries %>%
  filter(gender == 'male') %>%
  group_by(employment_category, gender) %>%
  summarise(avg_salary = mean(current_salary))
  

```

Q15

```{r}

# Find the number of white females, white males, non-white females and non-white males.

salaries %>%
group_by(gender, is_white) %>%
  count()
      


```


Q16

```{r}

# What is happens when we use summary statistics like mean with mutate? mutate(df, mean_age = mean(current_salary)) You may need to use View to see the whole data. Now use group_by with mutate and mean. What do you see?

salaries %>%
  mutate(mean_salary = mean(current_salary)) %>%
  group_by(mean_salary, current_salary)
  

```



2 # Pipes

Q1


```{r}
# Find the average salary per educational level, for educational levels of 16 and below. Arrange the results from highest salary to lowest. Answer using pipes

salaries %>%
  filter(educational_level <= 16) %>%
  group_by(educational_level) %>%
  summarise(avg_salary = mean(current_salary)) %>%
  arrange(desc(avg_salary))


```

Q2

```{r}
# Find the average salary for each gender in each employment category. Exclude any employees with less than 2 years of work experience. Answer using pipes

salaries %>%
  filter(work_experience < 2) %>%
  group_by(gender, employment_category) %>%
  summarise(avg_salary = mean(current_salary))

```

Q3

```{r}
# For each employment category find the difference between the mean salary and the median salary. Arrange so that the greatest difference comes first. Answer using pipes. (The difference between mean salary and median salary gives us a measure of how skewed salaries are - see unit 1.)

salaries %>%
  group_by(employment_category) %>%
  summarise(salary_diff = mean(current_salary) -
            median(current_salary)) %>%
  arrange(desc(salary_diff))
  


```




















































































