---
title: "Halloween candy"
output: html_notebook
---

# Task 4 - Halloween Candy Data

# The data is in clean formt now we can use it to ananlyse 


```{r}

library(tidyverse)
library(dplyr)
library(stringr)
library(readr)
library(here)

```



```{r}
# Load data from first csv file 

halloween_candies <- 
  read_csv(here("clean_data/halloween_candies.csv"), guess_max = 1000001)



```




1.4.2 Analysis questions

Q1

```{r}
# What is the total number of candy ratings given across the three years

halloween_candies %>%
  drop_na()%>%
  group_by(ratings)%>%
  summarise(candy_ratings = n()) %>%
  summarise(total_ratings = sum(candy_ratings))
  
  
```


Q2

```{r}
# What was the average age of people who are going out trick or treating and the average age of people 3. not going trick or treating?

halloween_candies %>%
   group_by(going_out) %>%
   summarise(avg_age = mean(age, na.rm = TRUE))



```

Q3



```{r}
# For each of joy, despair and meh, which candy bar revived the most of these ratings?

  
halloween_candies %>%
  drop_na() %>%
  group_by(ratings, candies) %>%
  summarise(candy_ratings = n()) %>%
  filter(candies != "any_full_sized_candy_bar") %>%
  filter(candy_ratings == max(candy_ratings)) %>%
  top_n(1)
  

```


Q4

```{r}
# How many people rated Starburst as despair

halloween_candies %>%
  drop_na() %>%
  filter(candies == 'starburst') %>%
  group_by(candies, ratings) %>%
  summarise(starburst_ratings = n()) %>%
  filter(ratings == 'despair')
  
  

```

Q5

```{r}
# What was the most popular candy bar by this rating system for each gender in the dataset?

halloween_candies %>%
  drop_na() %>%
  filter(gender != "not given") %>%
  group_by(gender, candies) %>%
  summarise(candy_ratings = n()) %>%
  top_n(1)



```

Q6

```{r}

# What was the most popular candy bar in each year

halloween_candies %>%
drop_na(ratings) %>%
group_by(year, candies) %>%
summarise(popular_ratings = n()) %>%
top_n(1)


```

Q7 

```{r}
# What was the most popular candy bar by this rating for people in US, Canada, UK and all other countries

halloween_candies %>%
drop_na() %>%
filter(year != 2015) %>%
group_by(country, candies) %>%
summarise(candy_ratings = n()) %>%
arrange(desc(candy_ratings)) %>%
top_n(1)


```


























